/* n3ds_gx.c - GX -> PICA200 translation layer.
 *
 * PC equivalent: pc/src/pc_gx.c. Same architecture (single global state
 * struct + per-frame flush + draw dispatch); the backend is citro3d on
 * PICA200 instead of OpenGL.
 *
 * Current status: scaffold of the abstraction + one test triangle. The
 * actual GX_* entry points the decomp expects (GXSetViewport, GXBegin,
 * GXLoadPosMtxImm, GXSetTevColorIn, ...) are NOT implemented yet -- this
 * file just proves the citro3d pipeline is alive end-to-end. Next step is
 * adding those entry points one at a time, with this file as the
 * destination.
 *
 * Differences from pc_gx.c that matter for grep'ing later:
 *   - Shaders are PICA assembly (n3ds_default.v.pica), not GLSL.
 *   - The fragment stage is fixed-function; "TEV" lives in citro3d's
 *     C3D_TexEnv API and is capped at 6 stages (GX has up to 16).
 *   - Texture upload requires tiling to 8x8 morton blocks; see
 *     n3ds_gx_texture.c (TODO).
 *   - "EFB copy" becomes "render to an off-screen C3D_RenderTarget and
 *     bind it as a texture" in the next pass.
 */

#include <stdio.h>
#include <string.h>

#include "n3ds_platform.h"
#include "n3ds_gx_internal.h"

#ifdef __3DS__
/* Generated by picasso + bin2s from src/n3ds_default.v.pica. The header
 * declares the byte array and its size; the symbols come from the .shbin.o
 * generated alongside it. */
#include "n3ds_default_shbin.h"
#endif

N3DSGXState g_n3ds_gx = {0};

#ifdef __3DS__

/* --- Top-screen render target ---
 * Top screen is physically 400x240 but the GPU framebuffer is 240x400
 * (the display rotates it 90deg on present). C3D_RenderTargetCreate takes
 * (height, width) -- not (width, height) -- which is why we pass 240, 400.
 * Mtx_OrthoTilt bakes the rotation into the projection matrix so we can
 * keep using a normal (left, right, bottom, top) ortho mental model. */
static int n3ds_gx_create_top_target(void) {
    g_n3ds_gx.target_top = C3D_RenderTargetCreate(
        N3DS_TOP_HEIGHT, N3DS_TOP_WIDTH,
        GPU_RB_RGBA8, GPU_RB_DEPTH24_STENCIL8);
    if (!g_n3ds_gx.target_top) return 0;

    C3D_RenderTargetSetOutput(
        g_n3ds_gx.target_top, GFX_TOP, GFX_LEFT,
        GX_TRANSFER_FLIP_VERT(0)
        | GX_TRANSFER_OUT_TILED(0)
        | GX_TRANSFER_RAW_COPY(0)
        | GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8)
        | GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8)
        | GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_NO));
    return 1;
}

/* --- Shader load --- */
static int n3ds_gx_load_shader(void) {
    g_n3ds_gx.vshader_dvlb = DVLB_ParseFile(
        (u32*)n3ds_default_shbin, n3ds_default_shbin_size);
    if (!g_n3ds_gx.vshader_dvlb) return 0;

    shaderProgramInit(&g_n3ds_gx.program);
    shaderProgramSetVsh(&g_n3ds_gx.program, &g_n3ds_gx.vshader_dvlb->DVLE[0]);
    C3D_BindProgram(&g_n3ds_gx.program);

    g_n3ds_gx.uloc_projection = shaderInstanceGetUniformLocation(
        g_n3ds_gx.program.vertexShader, "projection");
    return 1;
}

/* --- Attribute layout: position (vec3) + color (vec4) --- */
static void n3ds_gx_setup_attrs(void) {
    C3D_AttrInfo* attrInfo = C3D_GetAttrInfo();
    AttrInfo_Init(attrInfo);
    AttrInfo_AddLoader(attrInfo, 0, GPU_FLOAT, 3); /* v0 = position */
    AttrInfo_AddLoader(attrInfo, 1, GPU_FLOAT, 4); /* v1 = color    */
}

/* --- TEV: stage 0 outputs the per-vertex primary color, untouched ---
 * Mirrors a minimal GX TEV configuration (GX_PASSCLR). Once the real
 * GXSetTevColorIn/Op path lands, this becomes a per-stage update from
 * the decomp's TEV state. */
static void n3ds_gx_setup_default_tev(void) {
    C3D_TexEnv* env = C3D_GetTexEnv(0);
    C3D_TexEnvInit(env);
    C3D_TexEnvSrc(env, C3D_Both, GPU_PRIMARY_COLOR, 0, 0);
    C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);
}

/* --- Render state --- */
static void n3ds_gx_setup_state(void) {
    /* Depth: off for now (we have no geometry that needs it). When real
     * draws land, this becomes a per-frame state derived from
     * GXSetZMode / GXSetZCompLoc. */
    C3D_DepthTest(false, GPU_GREATER, GPU_WRITE_ALL);

    /* Cull: off until we know which winding the decomp uses on this
     * platform. */
    C3D_CullFace(GPU_CULL_NONE);
}

#endif /* __3DS__ */

int n3ds_gx_init(void) {
#ifdef __3DS__
    if (g_n3ds_gx.initialized) return 1;

    printf("[GX] step 1: C3D_Init\n");
    if (!C3D_Init(N3DS_GPU_CMDBUF_SIZE)) {
        printf("[GX] C3D_Init failed\n");
        return 0;
    }
    printf("[GX] step 2: create top RT\n");
    if (!n3ds_gx_create_top_target()) {
        printf("[GX] render target alloc failed\n");
        C3D_Fini();
        return 0;
    }
    printf("[GX] step 3: load shader\n");
    if (!n3ds_gx_load_shader()) {
        printf("[GX] shader load failed\n");
        C3D_RenderTargetDelete(g_n3ds_gx.target_top);
        C3D_Fini();
        return 0;
    }
    printf("[GX] step 4: attr info\n");
    n3ds_gx_setup_attrs();
    printf("[GX] step 5: default TEV\n");
    n3ds_gx_setup_default_tev();
    printf("[GX] step 6: render state\n");
    n3ds_gx_setup_state();

    printf("[GX] step 7: projection matrix\n");
    /* Orthographic projection covering [-1,1] in both axes, with the 90deg
     * top-screen rotation baked in (last arg = true). Triangle vertices in
     * the test draw are authored in this clip space. */
    Mtx_OrthoTilt(&g_n3ds_gx.projection,
                  -1.0f, 1.0f, -1.0f, 1.0f, 0.0f, 1.0f, true);

    printf("[GX] step 8: VBO alloc\n");
    /* VBO: pre-allocate space for a handful of test vertices. Real game
     * draws will reallocate / stream through this. linearAlloc is required
     * for buffers the GPU reads. */
    g_n3ds_gx.vbo_capacity = 256;
    g_n3ds_gx.vbo = linearAlloc(g_n3ds_gx.vbo_capacity * sizeof(N3DSVertex));
    if (!g_n3ds_gx.vbo) {
        printf("[GX] VBO linearAlloc failed\n");
        return 0;
    }

    printf("[GX] step 9: BufInfo\n");
    C3D_BufInfo* bufInfo = C3D_GetBufInfo();
    BufInfo_Init(bufInfo);
    BufInfo_Add(bufInfo, g_n3ds_gx.vbo, sizeof(N3DSVertex), 2, 0x10);

    g_n3ds_gx.initialized = 1;
    printf("[GX] init ok\n");
    return 1;
#else
    return 0;
#endif
}

void n3ds_gx_shutdown(void) {
#ifdef __3DS__
    if (!g_n3ds_gx.initialized) return;

    if (g_n3ds_gx.vbo) {
        linearFree(g_n3ds_gx.vbo);
        g_n3ds_gx.vbo = NULL;
    }
    shaderProgramFree(&g_n3ds_gx.program);
    if (g_n3ds_gx.vshader_dvlb) {
        DVLB_Free(g_n3ds_gx.vshader_dvlb);
        g_n3ds_gx.vshader_dvlb = NULL;
    }
    if (g_n3ds_gx.target_top) {
        C3D_RenderTargetDelete(g_n3ds_gx.target_top);
        g_n3ds_gx.target_top = NULL;
    }
    C3D_Fini();

    g_n3ds_gx.initialized = 0;
#endif
}

void n3ds_gx_begin_frame(void) {
#ifdef __3DS__
    if (!g_n3ds_gx.initialized) return;

    C3D_FrameBegin(C3D_FRAME_SYNCDRAW);

    /* Dark slate background so the triangle is obviously not the only
     * thing that changed. */
    C3D_RenderTargetClear(g_n3ds_gx.target_top, C3D_CLEAR_ALL,
                          0x202060FF, 0);
    C3D_FrameDrawOn(g_n3ds_gx.target_top);

    /* Projection uniform every frame -- cheap, and means the matrix can
     * eventually animate (camera, widescreen adjust, ...). */
    C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER,
                     g_n3ds_gx.uloc_projection,
                     &g_n3ds_gx.projection);
#endif
}

void n3ds_gx_end_frame(void) {
#ifdef __3DS__
    if (!g_n3ds_gx.initialized) return;
    C3D_FrameEnd(0);
#endif
}

void n3ds_gx_draw_test_triangle(void) {
#ifdef __3DS__
    if (!g_n3ds_gx.initialized) return;

    /* Three vertices, clip-space coords. RGB primaries so we can tell at a
     * glance whether attribute loaders + TEV are wired up correctly: if
     * the triangle is solid red, the color attribute didn't reach the
     * shader; if colors are wrong, TEV is misconfigured. */
    N3DSVertex* v = (N3DSVertex*)g_n3ds_gx.vbo;
    v[0].pos[0] =  0.0f; v[0].pos[1] =  0.8f; v[0].pos[2] = 0.5f;
    v[0].clr[0] = 1.0f;  v[0].clr[1] = 0.0f;  v[0].clr[2] = 0.0f; v[0].clr[3] = 1.0f;

    v[1].pos[0] = -0.8f; v[1].pos[1] = -0.8f; v[1].pos[2] = 0.5f;
    v[1].clr[0] = 0.0f;  v[1].clr[1] = 1.0f;  v[1].clr[2] = 0.0f; v[1].clr[3] = 1.0f;

    v[2].pos[0] =  0.8f; v[2].pos[1] = -0.8f; v[2].pos[2] = 0.5f;
    v[2].clr[0] = 0.0f;  v[2].clr[1] = 0.0f;  v[2].clr[2] = 1.0f; v[2].clr[3] = 1.0f;

    C3D_DrawArrays(GPU_TRIANGLES, 0, 3);
#endif
}
